### ISSUE TITLE
Sensor lookup error

### ISSUE THREAD

**Issue by eikeschott** [Nature40/pysensorproxy#13]
```
Traceback (most recent call last):
  File "/usr/local/bin/sensorproxy", line 11, in <module>
    load_entry_point('sensorproxy==0.1', 'console_scripts', 'sensorproxy')()
  File "/usr/local/lib/python3.5/dist-packages/sensorproxy/app.py", line 177, in main
    proxy = SensorProxy(args.config, args.metering)
  File "/usr/local/lib/python3.5/dist-packages/sensorproxy/app.py", line 71, in __init__
    self._test_metering()
  File "/usr/local/lib/python3.5/dist-packages/sensorproxy/app.py", line 87, in _test_metering
    self._meter(sensor_name, params)
  File "/usr/local/lib/python3.5/dist-packages/sensorproxy/app.py", line 90, in _meter
    sensor = self.sensors[sensor_name]
KeyError: 'mic'
```

**Comment by jonashoechst** [comment]
closed by 742527c
